// flow-typed signature: 337e471c15af0484f3640638f8676d9a
// flow-typed version: <<STUB>>/@combine-labs/combine-polaris_v0.1.5/flow_v0.74.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@combine-labs/combine-polaris'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@combine-labs/combine-polaris' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@combine-labs/combine-polaris/embedded' {
  declare module.exports: any;
}

declare module '@combine-labs/combine-polaris/esnext/index' {
  declare module.exports: any;
}

declare module '@combine-labs/combine-polaris/esnext/server' {
  declare module.exports: any;
}

declare module '@combine-labs/combine-polaris/index.es' {
  declare module.exports: any;
}

// Filename aliases
declare module '@combine-labs/combine-polaris/embedded.js' {
  declare module.exports: $Exports<'@combine-labs/combine-polaris/embedded'>;
}
declare module '@combine-labs/combine-polaris/esnext/index.js' {
  declare module.exports: $Exports<'@combine-labs/combine-polaris/esnext/index'>;
}
declare module '@combine-labs/combine-polaris/esnext/server.js' {
  declare module.exports: $Exports<'@combine-labs/combine-polaris/esnext/server'>;
}
declare module '@combine-labs/combine-polaris/index.es.js' {
  declare module.exports: $Exports<'@combine-labs/combine-polaris/index.es'>;
}
declare module '@combine-labs/combine-polaris/index' {
  declare module.exports: $Exports<'@combine-labs/combine-polaris'>;
}
declare module '@combine-labs/combine-polaris/index.js' {
  declare module.exports: $Exports<'@combine-labs/combine-polaris'>;
}
